Npm publish
FilledStacks/firebase-backend pull request #1
Opened 2021-02-26 23:08 UTC by llewellyncollins

Setup the npm automated publish. 

I can't test this locally as I need to be logged in to npm as filledstacks

When this PR is merged it should publish the package @0.1.1

2021-02-28 16:18 UTC, FilledStacks requested changes
Only the scope left that's not updated.

2021-02-28 16:18 UTC, FilledStacks commented on .github/workflows/package.yml
> -          scope: "@llewellyncollins"
scope is still llewellyncollins and not filledstacks

2021-02-28 19:12 UTC, llewellyncollins commented on .github/workflows/package.yml
> -          scope: "@llewellyncollins"
Yeah, that was a deletion. I don't think the scope is required when publishing to npm

2021-03-01 03:02 UTC, FilledStacks approved these changes

2021-03-01 03:02 UTC, merged