feat: Adds support for runWith options
FilledStacks/firebase-backend pull request #20
Opened 2021-03-26 20:25 UTC by adamschnaare

2021-03-28 07:56 UTC, vincenttan83 approved these changes

2021-03-28 14:07 UTC, FilledStacks requested changes
Nice addition! 

I'm a bit confused with passing the options into the endpoint if it's not set anywhere. But I do see in the FunctionParser we read it directly from the file. 

Could you do a short explainer how this is implemented and why options are not required to be saved in the Endpoint instance constructed.

2021-03-28 14:07 UTC, FilledStacks commented on src/models.ts
> +    public options?: EndpointOptions
Reviewing things on github is terrible. I just want to check I'm not missing anything. Are the options ever saved anywhere? I don't see it assigned to anything at anytime.

2021-04-03 02:09 UTC, adamschnaare commented on src/models.ts
> +    public options?: EndpointOptions
@FilledStacks , apologies on the delay. Sure - here's a quick explanation.

Here's a standard use case:
```js
export default new Post((req: Request, res: Response) => {
  const cardNumber = req.body["card_number"];
  const cardHolder = req.body["card_holder"];
  const token = `${cardNumber}_${cardHolder}`;

  return res.status(201).send({ token });
});
```
Nothing you don't need. Pass in the function handler and go on our merry way.

Since this PR is trying to solve a use case that might not be default, we put the options at the end, and make them , well..optional.

```js
const options: EndpointOptions = {
  runWith: {
    timeoutSeconds: 540,
    memory: "2GB",
  },
};

export default new Post((req: Request, res: Response) => {
  const cardNumber = req.body["card_number"];
  const cardHolder = req.body["card_holder"];
  const token = `${cardNumber}_${cardHolder}`;

  return res.status(201).send({ token });
}, options);
```
Right now, `runWith` is the only option that seems to be needed - but it feels conventional to represent them as a generic `options` object - something we can expand as needed.

2021-04-05 05:38 UTC, FilledStacks commented on src/models.ts
> +    public options?: EndpointOptions
@adamschnaare thanks for the details that helps but still doesn't answer my question. I don't see the options ever assigned in the constructor. I'm new to type script so I might be missing something but shouldn't the options be assigned internally to the endpoint value when constructing it?

2021-04-06 17:43 UTC, adamschnaare commented on src/models.ts
> +    public options?: EndpointOptions
Apologies! Yes, in Typescript you can assign and declare in the constructor function signature. It is meant to eliminate the boilerplate of :

SO instead of:
```js
class SOmeClass{
let someVariable;
  constructor(someVar){
    this.someVariable = someVar
  }
}
```
you can now:

```js
class SOmeClass{
  constructor(private someVar){}
}
```

All you have to do is declare the access modifier (`public`, `private`, etc...)

That said, the assignment is located here: https://github.com/FilledStacks/firebase-backend/blob/f6603165c105e25408e4264ba856133e772f7e56/src/models.ts#L50

2021-04-07 08:32 UTC, FilledStacks commented on src/models.ts
> +    public options?: EndpointOptions
Thank you! Perfect. Then I'm happy with this. I'll merge this in now. Will make a release tonight.

2021-04-07 08:32 UTC, FilledStacks approved these changes

2021-04-07 08:33 UTC, merged