Maintenance Commit w/ Small Changes
FilledStacks/firebase-backend pull request #7
Opened 2021-03-18 14:13 UTC by mxttwoods

- ```eslint --fix```
- spell check
- vscode extensions list
- editorconfig
- dependabot tooling
- fix readme

2021-03-18 14:28 UTC, mxttwoods commented
Cheers!

2021-03-18 16:52 UTC, mxttwoods commented
Also,

Your killing it on YouTube.

Keep up the good work!

2021-03-19 13:14 UTC, FilledStacks commented
Thanks. I'm so happy about the involvement from the backend community. I'll merge this in when I'm back on the open source work. Thanks so much for all the efforts. I really appreciate it.

2021-03-21 07:58 UTC, FilledStacks requested changes
Thanks! 

Biggest concern for me is the `/** @type {*} */` comments for the vars in the functions. I don't think they are necessary. They don't provide a lot of additional help when working in this package. 

Any specific reason they were added?

2021-03-21 07:58 UTC, FilledStacks commented on src/functionParser.ts
> +      /** @type {*} */
Hey, I don't like having these comments in between the source code for local variables. What exactly does this do for us?

2021-03-21 13:53 UTC, mxttwoods commented
It's just a quick type reference my editor generated. Happy to clean those up as your right; it doesn't provide any info other than {any} which is inherit.

2021-03-21 14:05 UTC, mxttwoods commented on src/functionParser.ts
> +      /** @type {*} */
no problem! cleaned it up

2021-03-21 14:06 UTC, mxttwoods commented
Have a look now! Thanks for the feedback.

2021-03-21 16:22 UTC, mxttwoods commented
Sorry I know that's a lot to review, hoping to see this project go 1.0.0 soon! 

Cheers

2021-03-23 15:36 UTC, mxttwoods commented
Let me know if you need another commit to merge properly.

2021-03-23 15:41 UTC, merged

2021-03-23 15:41 UTC, FilledStacks commented
Thanks @mxttwoods much appreciated!

2021-03-23 15:56 UTC, mxttwoods commented
> Thanks @mxttwoods much appreciated!

i'll try and get ci/cd going this week. 

Cheers