refactor: Adds request types as Classes
FilledStacks/firebase-backend pull request #8
Opened 2021-03-18 19:15 UTC by adamschnaare

I made a few changes to hopefully eliminate some boilerplate / potential spots for errors in authoring:
```
import { Request, Response } from "express";
import { Post } from "firebase-backend";

export default new Post((req: Request, res: Response) => {
...
});
```

Now when authoring a restful endpoint:
1. You can just use `Post`, 'Get`, etc... instead of `Endpoint([name],RequestType[TYPE],...)`
2. You don't need to specify the name - that comes from the filename itself

I also did a little cleanup in the logs and function structure.

2021-03-18 19:16 UTC, adamschnaare commented
Btw, this is kind of a proposal - feel free to reject if it isn't the way you intended this to be used.

2021-03-18 19:17 UTC, adamschnaare commented
Oh, and also I forgot - now in the Reactive Functions, you can just export the default function like so:
```js
import * as functions from "firebase-functions";

export default functions.firestore
  .document("users/{userId}")
  .onCreate((usersSnapshot, context) => {...});
```

2021-03-19 11:57 UTC, Runner-dev approved these changes
This is a great commit that also removes unnecessary middleware, making the restful requests code faster. Should definitely be approved

2021-03-19 13:16 UTC, FilledStacks commented
Thanks everyone! I really appreciate all the interaction and involvement. I'll review and merge this in soon. Will get back to open source work soon. 

I really appreciate the help with the PR's!

2021-03-19 18:04 UTC, adamschnaare commented
@Runner-dev , yeah I removed the express middleware that is now deprecated, yep.

2021-03-21 07:54 UTC, FilledStacks requested changes
I really like the changes to allow for removing the boilerplate! That's a great refactor. 

The same for using the fileName as the actual function name. That's how it was originally implemented and then the dev that moved it over to this package thought it would be better if we allowed them to supply the name. But that was assuming that everyone wouldn't want to follow the intended file structure and naming conventions. 

There's a few concerns that I have in the reviews below. The biggest one being given the users using this package (no matter how small they are) a chance to change to the newest api in a non forceful manner. We can deprecate the name (if possible) and tell them that they should instead use the updated way of defining an endpoint. 

Let me know if anything is unclear. I should be more active from next week.

2021-03-21 07:54 UTC, FilledStacks commented on src/models.ts
> -  name: string;
I think  we should leave this here and give the users the option to use this as it's been instructed in the original video / setup. 

I will start recommending the new way of doing things and write that in the readme as well. For now we need to allow them to use it as shown in the video. We can add a deprecation notice / doc on the name param and tell them the new preferred way to handle it.

2021-03-21 07:54 UTC, FilledStacks commented on src/functionParser.ts
> +      const functionName = filePath.name.replace('.function', '');
I'm not sure that this will work as you'll end up with `fileName.js` and not `fileName` on its own. I will test locally to make sure it works.

2021-03-22 19:17 UTC, adamschnaare commented on src/models.ts
> -  name: string;
Ah, yes. Great point. I was not thinking of anything other than moving forward. I'll rewrite that to handle the backwards compatibility, but label it as deprecated.

2021-03-22 19:21 UTC, adamschnaare commented on src/functionParser.ts
> +      const functionName = filePath.name.replace('.function', '');
From what I can tell, the `fileName` will end up being an object like:
```js
{
  root: '/',
  dir: '.../backend/functions/lib/users/reactive',
  base: 'onUserCreated.function.js',
  ext: '.js',
  name: 'onUserCreated.function'
}
```

`name` is what we can rely on. `ext` is explicitly the file extension.

2021-03-22 19:26 UTC, adamschnaare commented on src/models.ts
> -  name: string;
Also, I modified the constructor to use the TS shorthand for declaring and assigning class parameters.

2021-03-23 07:36 UTC, FilledStacks commented on src/functionParser.ts
> +      const functionName = filePath.name.replace('.function', '');
Got it! I through we're using the full path name. My mistake. This should work then.

2021-03-23 07:43 UTC, FilledStacks approved these changes
LGTM! Will merge and test

2021-03-23 07:50 UTC, merged

2021-03-23 10:52 UTC, FilledStacks commented
@adamschnaare Did you test this locally? I'm struggling to get it working using `npm run link` and doing a link in the boxtout project. 

Can you see without changing anything if it'll work in this project. You can clone and test the latest code on the project in `src/backend/functions`

2021-03-23 11:30 UTC, FilledStacks commented
I want to confirm this works as well as push proper readme with the update. I'll start with the readme now. You've already done a lot @adamschnaare , if you can confirm boxtout project runs fine with this update then I'll push this out.

2021-03-23 13:04 UTC, adamschnaare commented
@FilledStacks I did test it locally. I also had issues using `npm link`. Typescript was not able to compile. I think it may be a conflicting .tsconfig setting or something. I got it to work by cloning the repo right into the `functions/node_modules` directory. Kinda hacky, but we shouldn't need to mess with this module too often.

I tested the code in the `boxtout` example and it is working as is and if using the newer abstractions of `Post, Get`, etc...

2021-03-23 15:28 UTC, FilledStacks commented
great @adamschnaare I will complete the readme and then push that up probably tomorrow. Work is a bit hectic the past few days.